name: Poify/Unpoify

on:
  push:
    paths:
      - .bgforge.yml
      - .github/workflows/poify.yml
      - "ascension/lang/**"
  pull_request:
    paths:
      - .bgforge.yml
      - .github/workflows/poify.yml
      - "ascension/lang/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Poify/Unpoify
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        uses: BGforgeNet/msg2po@dev
        with:
          poify: true
          unpoify: true

      - name: Poify/Unpoify PR Testing
        if: (github.ref != 'refs/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request'
        uses: BGforgeNet/msg2po@dev
        with:
          poify: true
          unpoify: true
          push: false
